// Stellar
export const USDC_TRUSLINE =
  "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5";

export const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL || "https://dev.api.trustlesswork.com";

export const ADMIN_PK =
  process.env.NEXT_PUBLIC_ADMIN_PK ||
  "GDT26YDR47N3AC2RHMXPW65TM754XTMHTSE7RKSOP6W4NTOAFDERMWT3";

export const STELLAR_NETWORK =
  process.env.NEXT_PUBLIC_STELLAR_NETWORK || "testnet";

export const TRUSTLESS_API_KEY = process.env.NEXT_PUBLIC_TRUSTLESS_API_KEY!;

export const TRUSTLESS_PLATFORM_FEE =
  process.env.NEXT_PUBLIC_PLATFORM_FEE || "1.5";

// Supabase
export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;

export const SUPABASE_PUBLISHABLE_OR_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_OR_ANON_KEY!;

export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!;
