-- ============================================================================
-- 1. SETUP & EXTENSIONS
-- ============================================================================
create extension if not exists "uuid-ossp";

-- ============================================================================
-- 2. ENUMS (Safe Creation)
-- ============================================================================
DO $$ BEGIN
    create type user_role as enum ('contractor', 'freelancer');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type contractor_type as enum ('individual', 'company');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_type as enum ('requester', 'provider');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_legal_type as enum ('individual', 'company');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_business_type as enum ('freelance', 'agency', 'consultant', 'creator', 'team', 'company', 'other');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_industry_type as enum ('Technology', 'Artificial Intelligence', 'Web3 / Finance', 'Design / Creative', 'Consulting', 'Legal Services', 'Construction', 'Health', 'Media Production', 'Non Profit / Social', 'Manufacturing', 'Retail / Ecommerce', 'Travel / Hospitality', 'Real Estate', 'Other');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_member_role as enum ('owner', 'admin', 'member');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type organization_member_status as enum ('active', 'pending');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type project_status as enum ('draft', 'active', 'completed', 'cancelled');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type milestone_status as enum ('pending', 'in_progress', 'completed');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type contract_status as enum ('draft', 'pending_signature', 'signed', 'completed');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type notification_type as enum ('project_invitation', 'contract_signed', 'milestone_completed', 'payment_received');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    create type currency_code as enum ('usd', 'cad', 'mxn', 'bzd', 'crc', 'usd_sv', 'gtq', 'hnl', 'nio', 'pab', 'cup', 'dop', 'htg', 'jmd', 'ttd', 'bsd', 'bbd', 'xcd', 'gyd', 'ars', 'bob', 'brl', 'clp', 'cop', 'usd_ec', 'pyg', 'pen', 'uyu', 'ves', 'srd', 'eur_gf', 'eur', 'gbp', 'chf', 'pln', 'huf', 'dkk', 'sek', 'nok', 'isk', 'rub', 'try', 'bgn', 'hrk', 'mkd', 'rsd', 'bam', 'mdl', 'uah', 'byn', 'all', 'czk', 'nzd', 'kzt', 'amd', 'azn', 'kwd', 'lbp', 'gel', 'ron', 'ils', 'xpf');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ============================================================================
-- 3. TABLES (If Not Exists)
-- ============================================================================

create table if not exists public.continents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  code text not null,
  emoji text,
  description text
);

create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  iso2 text not null,
  iso3 text not null,
  numeric_code int,
  emoji text,
  continent_id bigint references public.continents(id),
  currency_code currency_code,
  currency_name text,
  currency_symbol text,
  phone_code text,
  available boolean default true
);

create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  role user_role,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone
);

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  created_by uuid references auth.users(id),
  type organization_type not null,
  legal_type organization_legal_type not null,
  name text not null,
  legal_name text not null,
  legal_id text not null,
  legal_phone text,
  bio text,
  avatar_url text,
  business_type organization_business_type,
  industry_type organization_industry_type,
  legal_country_id bigint references public.countries(id),
  legal_state text,
  legal_city text,
  legal_street_name text,
  legal_street_number int,
  legal_postal_code text,
  legal_suite text,
  legal_floor text
);

create table if not exists public.user_organization (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references public.profiles(id),
  organization_id bigint references public.organizations(id),
  email text not null,
  role organization_member_role default 'member',
  status organization_member_status default 'pending',
  joined_at timestamp with time zone
);

create table if not exists public.contractor_profiles (
  id uuid references public.profiles(id) primary key,
  contractor_type contractor_type not null,
  legal_name text,
  business_id text,
  address text,
  country text
);

create table if not exists public.freelancer_profiles (
  id uuid references public.profiles(id) primary key,
  full_name text,
  freelancer_id text,
  country text,
  address text,
  position text
);

create table if not exists public.projects (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone,
  contractor_id uuid references public.profiles(id) not null,
  freelancer_id uuid references public.profiles(id),
  title text not null,
  description text not null,
  total_amount numeric not null,
  expected_delivery_date date not null,
  status project_status default 'draft',
  contract_id text,
  contract_url text
);

create table if not exists public.milestones (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  project_id uuid references public.projects(id) on delete cascade not null,
  title text not null,
  description text,
  percentage int not null,
  status milestone_status default 'pending'
);

create table if not exists public.contracts (
  id uuid default uuid_generate_v4() primary key,
  project_id uuid references public.projects(id),
  contractor_id uuid references public.profiles(id),
  freelancer_id uuid references public.profiles(id),
  status contract_status default 'draft',
  contract_url text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

create table if not exists public.notifications (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  user_id uuid references public.profiles(id),
  type notification_type not null,
  title text not null,
  message text not null,
  read boolean default false,
  project_id uuid references public.projects(id)
);

create table if not exists public.evidences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  milestone_id uuid references public.milestones(id),
  description text,
  file_url text,
  file_name text,
  file_type text,
  created_by uuid references auth.users(id)
);

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================================================
-- 4. DATA POPULATION (Safe Inserts)
-- ============================================================================

-- Continents (Check before insert)
INSERT INTO public.continents (name, code)
SELECT 'North America', 'NA' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'NA');
INSERT INTO public.continents (name, code)
SELECT 'South America', 'SA' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'SA');
INSERT INTO public.continents (name, code)
SELECT 'Europe', 'EU' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'EU');
INSERT INTO public.continents (name, code)
SELECT 'Asia', 'AS' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'AS');
INSERT INTO public.continents (name, code)
SELECT 'Africa', 'AF' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'AF');
INSERT INTO public.continents (name, code)
SELECT 'Oceania', 'OC' WHERE NOT EXISTS (SELECT 1 FROM public.continents WHERE code = 'OC');

-- Countries (Check before insert)
INSERT INTO public.countries (name, iso2, iso3, continent_id, currency_code, phone_code)
SELECT 'United States', 'US', 'USA', id, 'usd', '1' FROM public.continents WHERE code = 'NA' AND NOT EXISTS (SELECT 1 FROM public.countries WHERE iso2 = 'US');

INSERT INTO public.countries (name, iso2, iso3, continent_id, currency_code, phone_code)
SELECT 'Argentina', 'AR', 'ARG', id, 'ars', '54' FROM public.continents WHERE code = 'SA' AND NOT EXISTS (SELECT 1 FROM public.countries WHERE iso2 = 'AR');

INSERT INTO public.countries (name, iso2, iso3, continent_id, currency_code, phone_code)
SELECT 'Spain', 'ES', 'ESP', id, 'eur', '34' FROM public.continents WHERE code = 'EU' AND NOT EXISTS (SELECT 1 FROM public.countries WHERE iso2 = 'ES');

INSERT INTO public.countries (name, iso2, iso3, continent_id, currency_code, phone_code)
SELECT 'United Kingdom', 'GB', 'GBR', id, 'gbp', '44' FROM public.continents WHERE code = 'EU' AND NOT EXISTS (SELECT 1 FROM public.countries WHERE iso2 = 'GB');

-- ============================================================================
-- 5. FUNCTIONS
-- ============================================================================

create or replace function get_user_organizations(p_user_id uuid)
returns json
language plpgsql
security definer
as $$
declare
  result json;
begin
  select json_build_object(
    'total', count(*),
    'organizations', coalesce(json_agg(o.*), '[]'::json)
  )
  into result
  from public.organizations o
  join public.user_organization uo on o.id = uo.organization_id
  where uo.user_id = p_user_id;

  return result;
end;
$$;

-- ============================================================================
-- 6. STORAGE BUCKETS & POLICIES (No Drop / No Alter)
-- ============================================================================

-- Create Buckets
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('organizations', 'organizations', true, 5242880, ARRAY['image/png','image/jpeg','image/jpg','image/webp']),
  ('contracts', 'contracts', false, 10485760, ARRAY['application/pdf']),
  ('evidences', 'evidences', false, 52428800, null)
on conflict (id) do nothing;

-- Create Policies Safely (Check existence first to avoid 42501 error on DROP)

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access to Organization Avatars' AND tablename = 'objects' AND schemaname = 'storage') THEN
        create policy "Public Access to Organization Avatars" on storage.objects for select using ( bucket_id = 'organizations' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Authenticated Users can Upload Avatars' AND tablename = 'objects' AND schemaname = 'storage') THEN
        create policy "Authenticated Users can Upload Avatars" on storage.objects for insert to authenticated with check ( bucket_id = 'organizations' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Users can Update Avatars' AND tablename = 'objects' AND schemaname = 'storage') THEN
        create policy "Users can Update Avatars" on storage.objects for update to authenticated using ( bucket_id = 'organizations' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth Access to Contracts' AND tablename = 'objects' AND schemaname = 'storage') THEN
        create policy "Auth Access to Contracts" on storage.objects for all to authenticated using ( bucket_id = 'contracts' ) with check ( bucket_id = 'contracts' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth Access to Evidences' AND tablename = 'objects' AND schemaname = 'storage') THEN
        create policy "Auth Access to Evidences" on storage.objects for all to authenticated using ( bucket_id = 'evidences' ) with check ( bucket_id = 'evidences' );
    END IF;
END $$;

-- New to add
ALTER TABLE public.organizations
ADD COLUMN IF NOT EXISTS custom_business_type text,
ADD COLUMN IF NOT EXISTS custom_industry_type text;

-- New to add
-- 1. Create a function to handle new user signups
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

-- 2. Create the trigger on auth.users
-- This ensures every FUTURE signup automatically gets a profile
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. FIX YOUR CURRENT USER (Backfill)
-- This inserts a profile for any existing user who is missing one
insert into public.profiles (id, email)
select id, email from auth.users
where id not in (select id from public.profiles);

-- New to add
-- 1. Add Soft Delete columns to 'organizations'
ALTER TABLE public.organizations
ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS deleted_by uuid references auth.users(id);

-- 2. Add Soft Delete columns to 'user_organization'
ALTER TABLE public.user_organization
ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS deleted_by uuid references auth.users(id);

-- 3. (Optional) Fix 'projects' table if it's missing them too, as best practice
ALTER TABLE public.projects
ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone,
ADD COLUMN IF NOT EXISTS deleted_by uuid references auth.users(id);
